# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title       : CWRUbotix
description : The home of Case Western Reserve University's undergraduate robotics club.
email       : robotics-exec@case.edu
base        : "https://cwrubotix.org" # the base hostname & protocol for use in the <base> html tag
baseurl     : "" # the subpath of your site, e.g. /blog
# url         : "http://cwrubotix.org" # the base hostname & protocol for your site
github_username : cwruRobotics
twitter_username: cwrubotix
# Build settings
markdown    : kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
